name: llm-candidate-rag
version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "${QDRANT_HTTP_PORT:-6333}:6333"
    volumes:
      - ../../data/qdrant:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:6333/ -T 3 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s